### ISSUE TITLE
Update license to make sure this software stays open source

### ISSUE THREAD

**Issue by kaplanlior** [maplibre/maplibre-gl-js#10]
## Motivation
https://github.com/mapbox/mapbox-gl-js/blob/main/CHANGELOG.md#%EF%B8%8F-breaking-changes

## Alternatives
Apache 2.0 at least. Would put MPL-2.0 or LGPL for discussion.

**Comment by nyurik** [comment]
I would prefer to keep it as open as possible. I am ok with the software staying as BSD/MIT style licenses because even if someone decides to relicense it, as long as software is moving forward, it will become increasingly difficult to backport the changes to some proprietary fork.

For example, let's say MapLibre has made some change to the code that Mapbox wants to use. Currently it will be very easy for Mapbox to apply them because the code is similar enough. But as the time goes on, the changes to MapLibre and to the Mapbox GL become so different, the complexity of back-porting the change from one fork to another would be prohibitively expensive.

On the other hand, making code licensing more restrictive doesn't actually do much in terms of improving ecosystem - the opposite is actually true because fewer corporate players will want to participate due to various restrictions that conflicts with their projects.

**Comment by lseelenbinder** [comment]
I agree with @nyurik. It's very unlikely the codebases will remain similar enough for other forks to take our work and relicense it—and it will always be freely available here. Corporate involvement is net positive, so I welcome any decision that makes it easier for companies to contribute.

**Comment by snickell** [comment]
I agree with @nyurik too, avoiding schismatic changes is important at this juncture too, and nothing beats "don't change anything" on that front

**Comment by nyurik** [comment]
seems we are in agreement, closing for now, please reopen/comment as needed.

**Comment by rbrundritt** [comment]
Just came back to close this, looks like some beat me to it. I consulted with my companies legal people and they said the current bsd license should be fine for enterprise. Internally I think I have to go through a little more work to get approvals to us bsd licensed projects but generally it's not an issue.
