### ISSUE TITLE
What should I do if no one answers?

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#102]
For outsiders like me it can become quickly frustrating if no one answers to my Issue or Pull Request. I guess new people come in with a lot of motivation but if nobody reacts to their input they will walk away and fragmentation will take place.

As a feedback I suggest to document in words how Issues and Pull Requests are treated by the maintainers of MapLibre. Explain the time it usually takes you to look over them and maybe implement automatic closing after 30 days of inactivity. By making a list of people who have commit rights it also gets easier for outsiders to ping someone who is a maintainer.

**Comment by JannikGM** [comment]
> maybe implement automatic closing after 30 days of inactivity

I'm very much against this. If anything, maintainers should be pinged automatically after 30 days without response.
Closing PRs by bot, without any response, is what drove us (the company that I work) away from upstreaming to mapbox already. We spent time preparing PRs but got nothing in return - it was very frustrating.

> For outsiders like me it can become quickly frustrating if no one answers to my Issue or Pull Request.

This is already such a problem for the company that I work for, that I consider abandoning maplibre. I'm having a contributing-to-mapbox dejavu already.
This is a serious issue.

We work in an agile environment and if upstreaming takes *weeks* instead of *hours*, then our company won't see any benefits of upstreaming. Our forks will diverge quickly and we'll not invest any time in maplibre.

I strongly suggest to bring down initial response and review time for PRs and issues.
If this is not done, maplibre can not succeed and it will quickly fragment the community.
At least prioritize it while the community is still growing.

> By making a list of people who have commit rights it also gets easier for outsiders to ping someone who is a maintainer.

I strongly agree. Reveal Slack and GitHub usernames of responsible people.

Having a list of maintainers / responsible people / experts for a given code-section would help to [avoid the responsibility problem](https://en.wikipedia.org/wiki/Diffusion_of_responsibility) and give new contributors an idea who they could ask for help.

**Comment by rbrundritt** [comment]
I agree with @JannikGM that automatically closing issues/PR's after a period of time is not desirable. Some items maybe be breaking changes that shouldn't be added until a future major version change, while others may be complex issues that aren't easy to fix and require a lot of time to address. Everyone participating in this project is doing so as a volunteer because they want to be a part of the community. 

I'm not a fan of having a list of maintainers/people who can make merges with contacts so that people can ping them when they want their stuff merged or get a status update. That can quickly make life miserable for these people and result in them stepping away from the project, I've seen this happen many times in the past with other projects. We have the issues tab for discussions of new features and issues, and the pull request tab for discussions on submitted additions to the project. At present the Project tab highlights the main initial focus which is to get the first fully stable and backwards compatible release out. For that release, new features are not a focus. We all want to jump in and add new features and fix that one bug that has hounded us for years, but we need to get the foundation of this project sorted first. There is a lot of work going on by many people. Some on the coding side, and some on the management side figuring out how to onboard this project with an open source foundation.

**Comment by wipfli** [comment]
Pinging people on slack worked out well for me. Looks like everyone is happy to help.
