### ISSUE TITLE
GeoJSON Source `setData` can take surprisingly long

### ISSUE THREAD

**Issue by JannikGM** [maplibre/maplibre-gl-js#106]
When passing a GeoJSON object to `setData`, it uses `JSON.stringify` on the main thread to send data to a worker:

https://github.com/maplibre/maplibre-gl-js/blob/256d1b898f1bd21f829977d4dec602a7f649f5a0/src/source/geojson_source.js#L262-L276

We recently ran into a situation where we generate a GeoJSON with about 200 `LineString` features with about 4500 geometry coordinates each.
Because of a design issue in our software, we use `setData` about 5 times per second.

The `JSON.stringify` for said data will take about 200ms each time. We experimentally did `JSON.parse` on that string (which will happen in the worker) and assume that it also takes about 200ms for said case.
At 5 updates per second, it's impossible for the worker to catch up, and the main thread blocks forever. The website becomes unresponsive.

---

While our software is to blame for the frequent and large updates, it also raises questions about mapbox GeoJSON performance.

Interestingly, generating the GeoJSON is much quicker than the `JSON.stringify`; I don't have exact numbers for this, but eyeballing in Chrome profiler, it's about 1/10th of the time (roughly 20ms I'd assume).

One assumption that we had was that `setData` would be mostly non-blocking and relatively fast. We saw mapbox talking about 100MB GeoJSON sources and dynamic updating of GeoJSON. It's obvious that the combination of this is bad, but we didn't expect it to be this bad - especially not on the main thread.

Here are some thoughts that I had while looking at this:

- Are there any source types which are faster, for locally generated content?
- Could we split data upload into smaller chunks or other ways to mitigate this potential issue on the main thread?
- How could one potentially improve maplibre to allow faster data submission to workers? What about a memory-optimized binary GeoJSON with `Float64Array` coordinates or similar?
- Can we potentially improve GeoJSON parsing in geojson-vt?
- Can we potentially improve cancellation in workers, to cancel an ongoing conversion earlier?
- Should there be a GeoJSON "diff" where one would only update modified features?
- It seems that each source is bound to one specific worker actor; so if that source is busy, it might have effect on other sources that share the same actor?
- Can we round feature location precision to slim the numbers down? We did this naively in a `JSON.stringify`-`replacer`, but it makes stringify even slower (in Chrome at least); we'll try it while generating the features next.

Things we do not want to resort to / things to avoid:

- Custom-layer for such data; potentially using existing solutions like deck.gl (although, does anyone have experience with this for such a use-case?)
- Splitting data into multiple sources (because we had this in the past, and it leads to bad repaint performance, which is another bottleneck for us; see #96)
- Change or simplify our features too much
- Generate tiles on server (it's not realistic to do, and we also have a lot of offline-data)

**Comment by JannikGM** [comment]
> How could one potentially improve maplibre to allow faster data submission to workers? What about a memory-optimized binary GeoJSON with Float64Array coordinates or similar?

I've now started looking into https://github.com/mapbox/geobuf for transferring data into the worker; observations so far:
- It still takes ~200ms (same as before); we can't see the promised "Very fast encoding and decoding — even faster than native JSON parse/stringify." from the geobuf README.
- Even if faster, it's not a drop-in replacement, because it looses some precision (If the analysis step was done separately from encoding, one could fallback to `JSON.stringify`, one more reason for https://github.com/mapbox/geobuf/issues/117).
- Adding a `allowLossy` parameter on `setData` is a bit more tricky, because we'd also need an API like that for source creation.
- We had invalid GeoJSON features which did not trip `geobuf.encode`, but `geobuf.decode` generated even less correct GeoJSON which then tripped geojson-vt (See https://github.com/mapbox/geobuf/issues/118).

You can find my changes here: https://github.com/JannikGM/maplibre-gl-js/commit/2369475fa86263036523cdc194163181f9ba2e50; suggestions welcome

**Comment by JannikGM** [comment]
In addition to the experiments with geobuf from my previous response, I've also tried the naive 'clone'. See PR #109 
Unfortunately, it will not fully resolve this issue.

Ideally we'd like this to consume even less time, so we *could* maintain *at least* 30FPS, even during a `setData`.

**Comment by JannikGM** [comment]
We found another bug in our software where we do redundant `setData` for GeoJSON sources.

We wonder if there's a way to hash the data on arrival in the worker, to then reject such updates immediately. I assume that a coarse check where one compares the metadata (id etc., instead of locations) could quickly avoid further checking for most source-updates. But for those very large redundant source updates, the check will likely be much faster than re-tiling everything.

We should have a warning mechanism in maplibre to make the user aware of such "bad" API use.

**Comment by rbrundritt** [comment]
A couple of thoughts:

- My first thought was around data coming in via a URL and downloading the data as a string, then passing that into the worker without the need for JSON.stringify, but there is already something like that implemented, so doesn't look like any optimizations to be made if your loading your data via URLs. 
- When working with raw GeoJSON objects, we could look at making use of Shared Array Buffer to efficiently pass data to a worker, however [browser support isn't great yet](https://caniuse.com/?search=SharedArrayBuffer). Another option might be to encode the data into a transferable object, but I'm not sure if this would be much more efficient than GeoBufs. 
- Looking around, there appears to be a few libraries designed to be faster alternatives to JSON.stringify (i.e. https://github.com/epoberezkin/fast-json-stable-stringify and https://gist.github.com/stereobooster/b2c9c543e794f3b927f82271b344ec72), however I would want to do a lot of tests before considering doing a swap like this. Also worth noting that since JSON.stringify is a commonly used native feature of the browser, it is likely to get faster over time.
- We ran into the issue with frequent updates to a GeoJSON source with Azure Maps (a high level wrapper around Mapbox/MapLibre). What we did is throttled the updates to the GeoJSON source using requestAnimationFrame. This ensured that data was only added to source when the UI thread was able to make the addition. Until then we cached the changes in memory. By doing this we were able to handle less performant implementations by end users without any noticeable impact (i.e. looping through a dataset and adding each item one by one). Perhaps we could implement something similar directly into the GeoJSON source.

**Comment by rbrundritt** [comment]
Looking around a bit more, looks like JSON.stringify is used in a lot of places within the code base. If we can find a good faster alternative that could easily be swapped back if needed, that might be a good option to improve performance in a number of places throughout the codebase. Might also be good to look at JSON.parse alternatives as well.

**Comment by HarelM** [comment]
@rbrundritt can you share the code you used to work around this issue?
I have a geojson source I use to show a recording made by the user (of his hike, drive, etc).
This geojson is updated each second from the GPS.
If the user records for a few hours it can get to thousand of points.
So when the routes get long the updates will take more and more time...

**Comment by JannikGM** [comment]
@HarelM there are (at least) 2 separate issues with large GeoJSON:

1. A large GeoJSON will be blocking the `setData` call on the main-thread (this issue); probably avoidable.
2. A large GeoJSON will take longer to be converted to vector tiles (in a worker, so this is fine) and will only slowly appear on the map (not sure if an issue exists); likely unavoidable but can be improved.

**Comment by rbrundritt** [comment]
@HarelM What we had done in Azure Maps to allow for smoother updates is to add in throttling using `requestAnimationFrame` so that if multiple update requests came in a short period of time, it wouldn't overwhelm the map and freeze it by constantly trying to repaint it. Below is a mockup of a class that does this (note I just threw this together without testing and couldn't simply pull out the source from Azure Maps as it has a lot of additional internal functionalities/classes that would require a lot more code than what's below).

```
class ThrottledDatasource() {
	
	constructor (map, sourceID) {
		this.geoJsonSource = this.map.getSource(this.sourceID);
		this.dataset = [];
		
		//Request animation ID, used to monitor updates.
		this.requestId = null;
	}
	
	/**
	* Add one or more features to the map.
	* @param {*} features A single feature, feature collection, or array of features.
	*/
	add(features) {
		if(Array.isArray(features)) {
			features.forEach((f) => {
				if(feature.type !== 'Feature'){
					//Assume it's a geometry and wrap as a feature.
					this.dataset.push({
						type: 'Feature',
						geometry: f,
						properties: {}
					});
				}
				
				this.dataset.push(f);
			});		
		} else if(features.type === 'FeatureCollection'){
			this.dataset = this.dataset.concat(features.features);
		} else if(feature.type === 'Feature'){
			this.dataset.push(feature);
		} else {
			//Assume it's a geometry and wrap as a feature.
			this.dataset.push({
				type: 'Feature',
				geometry: feature,
				properties: {}
			});
		}
		
		this.#updateSource();
	};
	
	/**
	* Remove one or more features to the map.
	* @param {*} features A single feature, feature collection, or array of features.
	*/
	remove(feature) {
		let idx;
	
		if(Array.isArray(features)) {
			features.forEach((f) => {
				if(feature.type !== 'Feature'){
					//Assume it's a geometry and wrap as a feature.
					f = {
						type: 'Feature',
						geometry: f,
						properties: {}
					};
				}
				
				this.#removeItem(f);
			});
		} else if(features.type === 'FeatureCollection'){		
			features.features.forEach((f) => {
				this.#removeItem(f);
			});
		} else if(feature.type === 'Feature'){
			this.#removeItem((feature);
		} else {
			//Assume it's a geometry and wrap as a feature.
			this.#removeItem({
				type: 'Feature',
				geometry: feature,
				properties: {}
			});
		}
		
		this.#updateSource();
	}
	
	/**
	* Overwrite all data in the datasource with one or more features to the map.
	* @param {*} features A single feature, feature collection, or array of features.
	*/
	setData(features) {
		this.dataset = [];
		this.add(features);
	}
		
	#removeItem(feature) {
		const idx = this.dataset.indexOf(feature);
		
		if(idx !== -1){				
			this.dataset.splice(idx, 1);
		}
	}
	
	/**
	* Updates the data source using requestAnimationFrame as a trottle so that we don't overwhelm the renderer.
	*/
	#updateSource() {
        if (this.requestId !== null) {
            return;
        } else {
            this.requestId = requestAnimationFrame(() => {
                this.geoJsonSource.setData({
					type: 'FeatureCollection',
					features: this.dataset
				});
                this.requestId = null;
            });
        }
	}
}
```

Here is how you would use this:

```
var ds = new ThrottledDatasource(map, 'myPointSource');

var point = { type: 'Point', coordinates: [0,0] };

//Add a point to the data source.
ds.add(point);

//Remove the point.
ds.remove(point);

//Overwrite all data in the data source with a new data set.
ds.setData(point);
```

In addition to the above, some other considerations:

- Consider changing your update frequency. 1 second update frequency is really high and only really used in map making type tasks. A vehicle travelling at 60 miles per hour would travel less than 30 yards in 1 second. In most typically tracking apps for vehicles, 15 seconds is usually the highest frequency used. At 60 mph, a vehicle would travel about a quarter mile (440 yards) in 15 seconds which might seem like a lot but to achieve that they would need to be on a stretch of highway where details points are often not needed. If you consider most fast runners and bikers would be going less than 10 miles per hour, the distance travelled in 15 seconds is less than 74 yards. Changing to 15 seconds would make your data size 15 times smaller. Now if you don't want to make that much of a change, even going to 5 seconds would make your data 5x smaller. Which would be about 88 yards when travelling at 60 miles per hour, and 25 yards at a 5 second interval. 
- Consider cleaning or optimizing the data you are bringing in. More than likely whatever you are tracking will have stops where there will be a lot of points collected for the same general location. Decide on a resolution for your data and remove duplicates. You can use a line simplification algorithm or simply compare your coordinates, rounded to 4 decimal places (~11 meter accuracy) and remove duplicates. 
- Consider how you render the data. Do you really need to show all the individual points in your app or is a line sufficient? or even a line and just the most recent individual points. If you can render most of your points as a line in your app, this will drastically reduce the number of features the map has to process.

**Comment by rbrundritt** [comment]
@HarelM For the preprocessing you could get away with only comparing the new coordinate the last coordinate in the line. If they are less than 5 meters apart either do no update or replace the last coordinate with the new one. 

I'm not a fan of frameworks like Angular and React due to performance impacts. Ran into the same issues with MVVM back in the Silverlight days. A lot of these frameworks are not designed for high throughput scenarios.

**Comment by HarelM** [comment]
Well... silverlight can't really be compared to modern frameworks... :-) it has earned its place is the hall of fame...
Angular is not great with performance, react is better as much as I know, but writing pure js is a suicide these days.
The app has a lot of screens, state management, ajax calls etc, it's not only the map.
You can see it here:
https://israelhiking.osm.org.il/
It's a vector map with a lot of details and the users expect accuracy when recording a route (I can't stress this enough, every month we have a new question in our facebook group asking why the calculated elevation of a route is different between different applications for example).
So accuracy is hard to compromise on.
In any case, as I said, I still need to understand what is the main problem before I set to fix it :-)

**Comment by HarelM** [comment]
After some debugging of my app I found out the problem is not with maplibre, but with my code (no surprise there :-)).
I tried to simplify my case and couldn't see any performance issues even after a lot of point were added to the line and even in 100ms update interval:
https://stackblitz.com/edit/angular-9nwniv?file=src%2Fdemo.ts

My issue can be seen here if any one finds this useful: -)
https://github.com/IsraelHikingMap/Site/issues/1749

**Comment by rbrundritt** [comment]
@HarelM Looking at your code I highly recommend replacing `setInterval` and `setTimeout` with `requestAnimationFrame` logic since you are animating data. It will make things more consistent and reliable, while using less memory. Here is a library that provides a drop-in replacement that is better: https://github.com/kambing86/requestanimationframe-timer This can save you a lot of headaches in the future as I've seen a lot of bugs that I couldn't reproduce on my machine being caused by `setInterval` and `setTimeout` as they work differently depending on the browser/device combination and the state of the machine sometimes.

**Comment by HarelM** [comment]
Thanks, but this is just an example I sketched, I don't have setInterval in my code, and try to avoid setTimeout as much as possible :-)
