### ISSUE TITLE
pointCoordinate in 3D returns null

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#1180]
Related to terrain 3D branch.
When terrain is on and passing pixel point `0,0` the pointCoordinate returns `null`.
This creates error in the console, something like can't value `x` of undefined.
This is not the case without terrain. point coordinate always returns a value.

**Comment by prozessor13** [comment]
Sometimes i also noticed coordinates outside the viewport (e.g. negative coordinates, may from moveend events when cursor is outside the map?). These cannot not be calculated, because they are outside the coords-framebufer. How to proceed with this?

* clamp coordinates to viewport
* use 2D function from transform.pointCoordinate
* ??

**Comment by HarelM** [comment]
I think "failing back" to 2d is the simplest solution right now unless you have a better idea.

**Comment by prozessor13** [comment]
No, i do not, as long the coords-framebuffer is used i think there is no better solution. When switching some day to ray/triangle intersection there may be the possibility to calculate correct point-coordinates outside the viewport (as long the necessary tiles are loaded).

**Comment by wipfli** [comment]
> When terrain is on and passing pixel point 0,0 the pointCoordinate returns null.

What is the easiest way to reproduce this?

**Comment by prozessor13** [comment]
Typing into the console:

    map.style.terrain.pointCoordinate({x:0, y:0})

returns `null`, but should be a MercatorCoordinate.

**Comment by HarelM** [comment]
Fixed in #1182
