### ISSUE TITLE
Remove a source referenced by terrain causes issues

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#1183]
When using adding a source, then setting a terrain to use it and then removing that source the terrain source cache still receives messages and there are console issues with source length for the url.

This is not a blocker as this is not a good way to use the terrain, having said that, there should be a warning or error saying that this is discouraged.

**Comment by HarelM** [comment]
Assigned M bounty
Link to parent Bounty: https://github.com/maplibre/maplibre/issues/189

**Comment by tempranova** [comment]
Happy to take this one!

**Comment by HarelM** [comment]
Sure.
I'll need to remember what I wrote here as this is somewhat similar to the previous one you did, if the solution is the same then obviously this doesn't need any more work.
Let me know what you see in terms of investigation on the cause of this.

**Comment by tempranova** [comment]
Here is an example of creating a style with a source for the terrain, setting the terrain on, and then removing the source (via the button): https://codesandbox.io/s/maplibre-gl-js-terrain-source-removed-c1cz8m?file=/src/index.js

I observe that there is a "flash" when the source is removed, ie, the terrain flattens and then goes to 3D again (presumably because the sourceCache is still getting messages and it's still fetching tiles). The terrain continues to render as you move around the map, and there are no visible errors in the console. 

If I'm understanding correctly, we should add a warning when the user removes the source being used for the active 3D terrain, but not change anything else? (even though it "continues to work" it's obviously asking for errors to happen eventually). Is there anything else I'm missing in terms of the "console issues with the source length for the URL" mentioned above?

Thanks!

**Comment by HarelM** [comment]
I should've created a reproducible jsbin instead of just writing the steps to reproduce...
But since I can't reproduce this, I believe this might no longer be an issue.
In any case, I'll be closing this issue, if we find a problem later on, we can always open another issue.
Thanks for taking the time to try and reproduce this.
