### ISSUE TITLE
LayerSpecification type: direct "source" object missing

### ISSUE THREAD

**Issue by cns-solutions-admin** [maplibre/maplibre-gl-js#1381]
2.2.0-pre.3:

According to the documentation the LayerSpecification "source" field can be a source specification.
However, the typescript type specifies it as only "string".

**Comment by cns-solutions-admin** [comment]
At least https://maplibre.org/maplibre-gl-js-docs/api/map/#map#addlayer allows a source object.
So maybe just the parameter to addLayer should allow the object?

**Comment by HarelM** [comment]
There was not real functionality change between 1.5 and 2.2 as  far as I remember.
In this issue the problem is with the misalignment between the docs and the typings I think here:
https://github.com/maplibre/maplibre-gl-js/blob/6b727918b136f8ee5bb0cecc0d5b617970beed13/src/ui/map.ts#L1925
Feel free to send a PR that changes both the docs and the code as it should be something like:
`@param {string | SourceSpecification} [layer.source] The data source for the layer.`
And the method's type for layer should be altered with a "compound" type I guess of `LayerSpecification & { source: SourceSpecification}` or something similar that typescript will approve... 
Thanks for looking into this! :-)
