### ISSUE TITLE
Map position jumps on moveend if 3D terrain is active

### ISSUE THREAD

**Issue by zdila** [maplibre/maplibre-gl-js#1492]
**maplibre-gl-js version**: 2.3.0

**browser**: Chrome, Vivaldi, Firefox

### Steps to Trigger Behavior

 1. create map with 3D terrain
 2. move map, or zoom it, or use `NavigationControl` to reset bearing to north (even if it is already)
 3. map will shift a little bit, sometimes also changes its zoom level (watch lat/lng/zoom changing in `moveend` event if you press reset bearing button several times). 

### Link to Demonstration

https://www.freemap.sk/~martin/hikingmap/#style=hiking&lat=48.65650020&lng=18.91571045&zoom=7.22&bearing=0.00&pitch=0.00&3d=true

Source code is plain, non-obfuscated.

The shift/zoom increases if you play with the map little more - move it, pan it, rotate it, change layers, turn 3D terrain on/off several times.

### Expected Behavior

Map position should be stable after move-end.

### Actual Behavior

Map shifts.

**Comment by HarelM** [comment]
Any help investigating this would be greatly appreciated. The terrain 3D code is still experimental and there are still some issues with it.

**Comment by prozessor13** [comment]
Hello,

the zoomlevel is changed because:
During panning the camera stays in the same height above sea-level, but the terrain under the camera changes, so the zoom-level has to be re-calculated on move-end, because the zoomlevel represents the distance between the center-coordinate and the camera-position.

the small pixel-jumps are related to rounding errors. the current implementation is not doing a raycast into the 3d-mesh to calculate coordinates, instead it renderes all coordinates rgb-encoded into a framebuffer, which can be later picked for spezific screen-pixels.

I have several ideas to fix this, but nothing concrete. Do you have eperience in this things, may can you help to fix this problem?

Regards. Max.

**Comment by zdila** [comment]
You can also test it on https://labs.maptiler.com/samples/maplibre/terrain/

1. open the page
2. press button labelled `1` (you can do it later several times)
3. press button labelled `2` (you can then jump between `1` and `2`)

If map is shifting very much after end of the animation then refreshing the page (which loads the map on te latest position) helps it.

In any case this 3D terrain feature is an amazing thing. Many thanks for implementing it :-).

**Comment by prozessor13** [comment]
Ok. Understand. We are talking from different jump problems ;). May my
today pull request will help. Can you please test it?

**Comment by zdila** [comment]
> We are talking from different jump problems ;).

I think you are right - `flyTo` to wrong position may be a different issue.

> May my today pull request will help. Can you please test it?

Now `flyTo` ends in the correct position, just the flying is little bit with the air turbulence simulation ;-). You can try on [my demo](https://labs.maptiler.com/samples/maplibre/terrain/).

**Comment by prozessor13** [comment]
It would be great if you can try the last changes in https://github.com/maplibre/maplibre-gl-js/pull/1514 and tell your results.

**Comment by zdila** [comment]
It is better but is still not ideal:

1. open https://labs.maptiler.com/samples/maplibre/terrain/#style=gray-shading&lat=49.16503761&lng=20.13770342&zoom=14.68&bearing=-141.64&pitch=72.14&3d=true
2. keep pressing button "9" - view (final map lat/lng coordinates) is slightly moving

Another thing:

1. switch between "9" and "10", back and forth
2. during the animation it once jumps during the flight

**Comment by prozessor13** [comment]
I think all the small jumps comes from the issue, that sceen-coordinates -> geographic-coordinates are done via hidden RGB encoded values (e.g. the coords-framebuffer). But with this logic you always getting small rounding errors, and in heavy terrain these rounding errors gets even worse.
So i think this a different issue, and this issue can be closed.

**Comment by prozessor13** [comment]
Ok, may the last small jump is related to this:

https://github.com/maplibre/maplibre-gl-js/pull/1514/files#diff-d626aec7548d249604d0505cfaed6100482c49aa039c0d56cbb10ca78a8bad2eR941

this may happens when terrain tiles loads during flight, and when the linear interpolation has to be adopted to the new, more exact, elevation values.

**Comment by HarelM** [comment]
@prozessor13 if you think this issue is fixed let's close it and open a new one more specific to the issues we identified here.

**Comment by prozessor13** [comment]
@zdila i did another checkin in the freezeElevation branch. Can you please test? thx!

**Comment by zdila** [comment]
@prozessor13 seems that 2nd testcase from https://github.com/maplibre/maplibre-gl-js/issues/1492#issuecomment-1231238164 is no more reproducible. Only the first testcase is.

**Comment by prozessor13** [comment]
i created a new issue fuer first issue: https://github.com/maplibre/maplibre-gl-js/issues/1596
because second issue is fixed, i close this issue.
