### ISSUE TITLE
Terrain should contribute to attribution

### ISSUE THREAD

**Issue by zdila** [maplibre/maplibre-gl-js#1513]
**maplibre-gl-js version**: 2.3.0

**browser**: all

### Steps to Trigger Behavior

 1. define terrain style with terrain source and set its `attribution`
 2. call `map.setTerrain` with that terrain source

### Expected Behavior

Terrain attribution should be shown in the map.

### Actual Behavior

No terrain attribution is shown in the map.

**Comment by acalcutt** [comment]
Does attribution actually work when only terrain is defined and not hillshade? I made a few test pages and the only one my attribution shows how is the one where I defined hillshade too. 

For example,

terrain in style (attribution does not show)
https://stackblitz.com/edit/web-platform-mzh76t?file=index.html

terrain added with addsource/setterrain (attribution does not show)
https://stackblitz.com/edit/web-platform-npstzn?file=index.html

terrain in style with hillshade (attribution shows)
https://stackblitz.com/edit/web-platform-26fwya?file=index.html

I don't think I ever noticed this because I also usually have hillshade using the same (but separate) source.

**Comment by zdila** [comment]
You can check https://labs.maptiler.com/samples/maplibre/terrain/#style=satellite&lat=48.61883911&lng=20.83645105&zoom=15.60&bearing=-21.60&pitch=72.50&3d=true - this uses the following style -source:https://labs.maptiler.com/samples/maplibre/terrain/styles/satellite.json and in JS I call `map.setTerrain('terrain');`

**Comment by acalcutt** [comment]
I looked into this a bit and made this test added a bunch of console.logs in the attribution code (that test page is here https://stackblitz.com/edit/web-platform-tbtq66?file=maplibre-gl.js,index.html )

It looks like this happens because the attibution code checks if SourceCache.used is true, but with terrain SourceCache.used is false. I looks like instead, a terrain layer has a SourceCache.usedForTerrain flag  that gets set to true when it is in use.
![image](https://user-images.githubusercontent.com/3792408/185614314-d3afb5d4-3dbe-432d-ac4e-0c36b46e1b75.png)

Right now, the code in https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/control/attribution_control.ts#L134 would ignore this source layer because used is false. 

In my test page I line 134 to
`if (sourceCache.used || sourceCache.usedForTerrain) {`
which seemed to show the attribution when terrain was used.
