### ISSUE TITLE
Show OSM attribution by default

### ISSUE THREAD

**Issue by tuukka** [maplibre/maplibre-gl-js#205]
OSM is an important data source for MapLibre. Users should be made aware when they are seeing OSM data. When data from OSM is displayed, the OSM attribution should be visible by default. This was discussed at SotM 2021 and matches OSMF's new guideline: https://lists.openstreetmap.org/pipermail/osmf-talk/2021-June/007914.html

As a usability improvement, tapping the attribution link should open a dialog (potentially with some information about OSM) and another button to confirm whether the user wants to move to openstreetmap.org.

**Comment by wipfli** [comment]
That's a nice idea. Would you like to make a pull request for this?

**Comment by lukashass** [comment]
> When data from OSM is displayed, the OSM attribution should be visible by default. This was discussed at SotM 2021 and matches OSMF's new guideline: https://lists.openstreetmap.org/pipermail/osmf-talk/2021-June/007914.html

To this point of displaying the attribution by default, I don't think the current behavior complies with the mentioned guideline because it __instantly__ "collapses when the map is less than 640 pixels wide" (see https://maplibre.org/maplibre-gl-js-docs/api/markers/#attributioncontrol).

As per the guideline:

> You may use a mechanism to fade/collapse the attribution under certain conditions:
>    - immediately with a dismiss interaction, for example clicking an ‘x’ in the corner of a dialog
>    - automatically on map interaction such as panning, clicking, or zooming
>    - automatically after five seconds. This also applies to splash screens or pop-ups.

I implemented the second option by replacing the non-compact attribution with a compact attribution on drag. Maybe something like this could be the default for maplibre?

```ts
map = new Map({
  attributionControl: false,
});

const attributionControl = new AttributionControl({ compact: false });
map.addControl(attributionControl);

map.on('drag', () => {
  if (map.hasControl(attributionControl)) {
    map.removeControl(attributionControl);
    map.addControl(new AttributionControl({ compact: true }));
  }
}
```

**Comment by acalcutt** [comment]
I made an attempt to make the attribution control more compliant with the "should be visible by default" requirement of openstreetmap with some changes to attribution_control.ts here ( https://github.com/acalcutt/maplibre-gl-js/blob/attribution_default_open_for_osm/src/ui/control/attribution_control.ts )

I made it so when the attribution goes to compact it defaults to being open.  I then used the idea above by @lukashass to close attributes on drag, so it will close when the screen is moved or when the compact button is clicked.

I haven't yet updated the associated test, but it likely needs some updating due to the change in behavior.
