### ISSUE TITLE
Offline map

### ISSUE THREAD

**Issue by malao98** [maplibre/maplibre-gl-js#207]
Hello! 

Im new to codding and also Maplibre. Would like to ask if its possible to run maplibre locally?

Thanks!

**Comment by HarelM** [comment]
I'm doing it using cordova. Probably possible also using electron.
Offline map are possible using the addProtocl feature.
So yes, in general.

**Comment by wipfli** [comment]
There is also maplibre-gl-native. What is your use case?

**Comment by malao98** [comment]
Im using it in react-map-gl. I replaced all references of mapbox-gl into maplibre-gl. I managed to run the examples in react-map-gl online without using mapboxaccesstoken, but I still cannot run the examples offline. 
![Screenshot from 2021-07-13 21-04-11](https://user-images.githubusercontent.com/82607000/125511467-2f59eb43-5394-44d2-ae1a-45a50c9e48b6.png)
From the image, you can find the default prop that im currently using. Is it because the mapstyle Im using is not local data, which need to be accessed online?

*ps : appreciate the replies. Thanks :)

**Comment by wipfli** [comment]
You need to be online to get the style and the tiles.

**Comment by ambientlight** [comment]
You can pass style json directly but you would need to have a service worker to cache the glyphs(prerendered fonts) and sprites(bundled icon bitmaps)

**Comment by wipfli** [comment]
I have been wondering how to use service workers with MapLibre GL JS for a while. Do you have an example @ambientlight ?

**Comment by ambientlight** [comment]
@wipfli: I don't have an actual example on hand, I can make one, but some info on how I did it previously:

You don't really need any additions to your client logic on top of maplibre. You just need to generate a service worker that will cache all requests to the endpoint that serves glyphs, sprites and tiles. Make sure the endpoint has CORS enabled otherwise Chrome will assign a big size penalty under `no-cors`. 

I relied on webpack as a bundler which has [workbox-webpack-plugin](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin) that can generate service workers. In webpack config plugins, it would look something like:

```ts
// import { GenerateSW } from 'workbox-webpack-plugin'

new GenerateSW({
    runtimeCaching: [{
       urlPattern: new RegExp('^http[s]*:/{2}your\.tile\.endpoint\.com/'),
       handler: 'cacheFirst',
    }],
    // might also need to add this as it has some small default If I remember correctly
    maximumFileSizeToCacheInBytes: 16777216
})
```

You will end up having a service worker generated in your `/dist` that will have something like:

```js
workbox.routing.registerRoute(/^http[s]*:/{2}your\.tile\.endpoint\.com\//, workbox.strategies.cacheFirst(), 'GET');
```

You then can consume it as easy as:

```
window.navigator.serviceWorker.register(`/sw.js`. { scope: `/`))
```
