### ISSUE TITLE
Unimplemented `distance` expression

### ISSUE THREAD

**Issue by cyrilchapon** [maplibre/maplibre-gl-js#2077]
### Context

I'm trying to color my symbols based on their distance from a point on a map (a marker of my own).
I landed on the documented [`distance` expression](https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/#distance) and naively tried to replace my `icon-color` with it.

**maplibre-gl-js version**: 2.4.0

**browser**: Chrome 108.0.5359.124

### Steps to Trigger Behavior

 1. Use the expression as below
 ```js
 [
    'interpolate', ['linear'],
    [
      'distance',
      {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [2, 40]
        }
      },
    ],
    100, '#E02F58',
    10000, '#000000',
  ]
 ```
 2. Read the console

### Link to Demonstration

PoC, working symbol with static color : https://jsfiddle.net/cpn1dkv8/
Not working symbol with distance based-color https://jsfiddle.net/cpn1dkv8/1/

### Expected Behavior

Since it's documented, I'd expect it to work like so.

### Actual Behavior

It's generating an error :

> Error: layers.[my-layer].icon-color[2][0]: Unknown expression "distance". If you wanted a literal array, use ["literal", [...]].

### Addendum

For what it's worth, the original mapbox-gl implementation seems to be blocked in a draft PR [here](https://github.com/mapbox/mapbox-gl-js/pull/10616) (and the feature is also documented in mapbox docs too).

**Comment by HarelM** [comment]
It might be that this is not fully supported as you said about the draft PR, I'm not sure.
I would start with a simpler example for the distance and see if that works. I know icon-color can use the priorities from a feature (using [get, ...]) but I'm not sure about distance and the combination of these two.

**Comment by wipfli** [comment]
Distance is the only expression that is only implemented in MapLibre GL Native and not in MapLibre GL JS, see the supported SDKs table in https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/#distance

**Comment by cyrilchapon** [comment]
Thanks @wipfli for pointing this, I'm so stupid !

------

Ok so I think this features's state is inherited from mapbox-gl before the fork. I dugg into [the draft PR](https://github.com/mapbox/mapbox-gl-js/pull/10616) a little bit; and apparently the feature is developed, but the bundle size bump involved is considered too high to allow a merge as-is. The feature has been marked as "postponed" in that sense.

"Bundle size bump too big" + "already implemented" sounds like a perfect fit for a plugin, in my mind. Doesn't it ?

**Comment by HarelM** [comment]
Yes, plugin is the right solution for bundle size issues.
I'm not sure how easy it will be to add an expression as a plugin, but if you manage to do it, or even create a PR that will allow to add expression as plugins it can open a world of opportunities.

**Comment by cyrilchapon** [comment]
Hey @HarelM ,

> I'm not sure how easy it will be to add an expression as a plugin
That was my thought. I never encountered such a plugin, so I guess it wouldn't be that easy.

> or even create a PR that will allow to add expression as plugins it can open a world of opportunities.
Indeed. That would be so much valuable.

I'm afraid I'm not familiar enough with the codebase, the cartography world and don't have enough time to give it a shot. Though I surely can help and start by documenting and researching a little bit.

Probably related :
- [mapbox#9462](https://github.com/mapbox/mapbox-gl-js/issues/9462) "Expression engine extension points"
- [maplibre#1295](https://github.com/maplibre/maplibre-gl-js/issues/1295) "Expression engine extension points"

**Comment by DevelWolf** [comment]
> I'm not sure how easy it will be to add an expression as a plugin, but if you manage to do it, or even create a PR that will allow to add expression as plugins it can open a world of opportunities.

To understand what's needed for a "distance"-plugin, I have patched a rudimentary implementation of `distance` expression, which only computes the distance between point features, into the current version of `maplibre-gl.js`. You can try it [here](https://jsfiddle.net/DevelWolf/y9t43rnm/9/).

As you can see, the implementation of `distance` needs access to the `EvaluationContext` ctx, more precisely the members `geometryType()` and `geometry()` to get the feature's pixel coordinates, and to member `canonical` of type `ICanonicalTileID` to convert the pixel coordinates to LonLat.

It would be quite easy to naively add a hook `Map.addExpressionType(...)` to dynamically add expression types to the library, but this would need to expose the `EvaluationContext` and member types, which I think is a bad idea.

### Considerations for a clean implementation

#### 1. Encapsulation of context access

There already is a `geometry-type` expression ([spec](https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/#geometry-type)), which delivers the ctx.feature.type as string.

We can easily add a expression `geometry` to the library, which returns the feature's geometry as an object, already converted from pixel coordinates to geographic coordinates.

#### 2. Providing a hook for adding native expression types

With "native" I mean the function will receive evaluated values of JS base type as arguments and has no access to the enviroment or other parts of the library at all.

```
Map.addNativeExpressionType( 'mean',
        'number', ['number', 'number'],
	(a, b) => return (a+b) / 2
);
```

```
Map.addNativeExpressionType( 'string-index-of',
	'number', ['string', 'string'],
	(needle, haystack) => return haystack.indexOf(needle)
);
```

```
Map.addNativeExpressionType( 'string-char',
	'string', ['string', 'number'],
	(s, index) => return s.charAt(index)
);
```

This way we can implement the distance computation as a native expression type:

```
Map.addNativeExpressionType( 'explicit-distance',
	'number', ['string', 'object', object],
	(geoType, geo, referenceFeature) => {
		//some math
		return distance;
	}
);
```

and use it:

```
['explicit-distance',
	['geometry-type'],
	['geometry'],
	{
		type: 'Feature',
		geometry: {
			type: 'Point',
			coordinates: [2, 40]
		}
	}
]
```

#### 3. Providing a hook for adding "macro expression" types

Unfortunately this way we cannot provide the `distance` expression type exactly as [specified in the documentation](https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/#distance), because the `distance` needs implicit access to the context.

To fix this, we could add "macro expressions", which would not be added to the list of available expressions, but used while compiling an expression; may be this way (I'm not sure about the syntax):

```
Map.addMacroExpressionType( 'distance', 1 /*one arg*/,
	[ 'explicit-distance', ['geometry-type'], ['geometry'], [1/*placeholder for arg 1*/] ]
```

Resulting in the expression

```
['distance',
	{
		type: 'Feature',
		geometry: {
			type: 'Point',
			coordinates: [2, 40]
		}
	}	
]
```

being replaced by and compiled as

```
['explicit-distance',
	['geometry-type'],
	['geometry'],
	{
		type: 'Feature',
		geometry: {
			type: 'Point',
			coordinates: [2, 40]
		}
	}
]
```

Heureka.

**Comment by HarelM** [comment]
@DevelWolf thanks for sharing your thoughts!
Can you maybe move your comment to: #1295? I think it will be better to discuss it there and have the distance as an example.

**Comment by DevelWolf** [comment]
> Can you maybe move your comment to: https://github.com/maplibre/maplibre-gl-js/issues/1295?

Sorry, but I don't know how to move a post; the “three dots” menu at the top does not show an entry “move”. Please feel free to move the post to where it belongs.

**Comment by DevelWolf** [comment]
This isn't exactly what I would name as “move”. :-)

**Comment by HarelM** [comment]
This will probably get release in the next version within a few days.
