### ISSUE TITLE
possible support for offscreen OffscreenCanvas

### ISSUE THREAD

**Issue by mrafei** [maplibre/maplibre-gl-js#239]
Considering the fact that maplibre library comes with a large bundle, loading map on the first page load is lowering 3 (SI, TTI and TBT) out of 6 metrics of Google PageSpeed. Map based websites now have to either go with Google Maps API which is not free or decide to not show map at first load.

One of the solutions could be using OffscreenCanvas  to move the rendering pipeline into a webworker to achieve smooth first page load.

This feature is also being tracked at mapbox-gl-js. I was wondering if there would be any plans in future to implement this feature.

thanks.

**Comment by HarelM** [comment]
I've seen in the code references to `OffscreenCanvas`. I have not clue what they mean or how to improve the above matrices but you are very welcome to try and hack this. :-)
Since mapbox code is not open source anymore there are no plans to take any code written there after version 1.13.

Your best bet would be to start investigating this and propose fixes/improvements/etc in the form of PRs. :-)

**Comment by birkskyum** [comment]
This includes an offscreen demo
https://github.com/wipfli/maplibre-canvas-labels
