### ISSUE TITLE
Fork @types/mapbox-gl-js as well and possible inegrate directly with this repo

### ISSUE THREAD

**Issue by GarrettCannon** [maplibre/maplibre-gl-js#24]
Moving this issues from the old repo into the new one.

Hello,

I definitely appreciate the efforts here. My suggestion would be to fork https://www.npmjs.com/package/@types/mapbox-gl as well to be used with this library.
Ideally it could be fully merged into this repo to further reduce fragmentation.
I don't know how the maintainers want to go about this, but if I can help let me know.

Thanks!

**Comment by snickell** [comment]
Key questions: do we have any developers with a typescript interest + good type system knowledge + want to continue to maintain and spend time on these? If we do, I think eventually having types in the same org is a good idea, if not, DefinitelyTyped might do a better job than us, and perhaps we should just consider reaching out to them?

**Comment by nyurik** [comment]
I have done some typescripting, and generally would prefer us to eventually move all maplibre to `*.ts`. I wonder how others feel about it (this should probably be a separate issue though, with a bunch of subissues)

**Comment by tomchadwin** [comment]
> do we have any developers with a typescript interest + good type system knowledge

@jameslmilner

**Comment by HarelM** [comment]
I'm interested. I'm working only with typescript.
Feel free to tag me for any typescript issues.
I feel strongly about using typescript instead of flow (that's what's in here...? almost didn't find any library that uses it...) and would like to help out with the migration if this is something that more people are interested in (as Said, this is another issue).
Once you convert the code to typescript the definitions are for free :-)
But until then, it shouldn't be hard to move the definition files here and reference them from package.json file.

**Comment by GarrettCannon** [comment]
Same here, I'm pretty experience with TS and would be willing to help out where needed. Just point me in the right direction!

**Comment by zakjan** [comment]
Same here. I have a concern about dependent libraries with Mapbox as peer dependency. Examples: various wrappers for frameworks (Vue, React, ...), or my [cytoscape-mapbox-gl](https://github.com/zakjan/cytoscape-mapbox-gl). They can't simply update to Maplibre, because it would prevent devs using them with Mapbox 2. Either dependent libraries need to split into two and duplicate all further changes, or support both Mapbox and Maplibre in the same library. Since the API is stable, I think there is no need to split, if we can describe in TS type system that a dependant library can use both Mapbox and Maplibre.  There is a similar situation in [graphology libraries](https://graphology.github.io/#standard-library), they all depend on [graphology-types](https://github.com/graphology/graphology-types), but the current solution feels clunky. I'm wondering if there is a better option.

**Comment by HarelM** [comment]
The libraries will eventually diverge I believe, so if the library here had its typings inside there won't be a problem...

**Comment by zakjan** [comment]
There is 500 libraries depending on Mapbox. https://www.npmjs.com/package/mapbox-gl?activeTab=dependents It doesn't seem realistic to update them all. Another option would be to use npm/yarn alias.

**Comment by snickell** [comment]
This library is not meant to be a drop-in replacement for mapbox-gl-js v2, that is an impossible chase

**Comment by snickell** [comment]
We'll explore updating bindings in v1.14, for v1.13 we're focused on as drop-in as possible, but generally, yes aliases are probably the way to go here.

I suspect many/most open source binding authors will over the long term prefer not to become bindings to a closed source project, but for now, they'll want to "straddle" and aliases give a good way to do that wrt to peer deps.

**Comment by folke** [comment]
[@types/maplibre-gl](https://www.npmjs.com/package/@types/maplibre-gl) has just been released on npm. It's a copy of the mapbox-gl types for 1.13.0

**Comment by klokan** [comment]
Can we update to 0.14.0 please?

@folke 

Is this possible to automate generation for these with the release automation - as it was done in #95 ?

**Comment by HarelM** [comment]
Is there an objection to integrate the typings file into this repository? I don't see a value in creating an npm @types package. Am I missing any thing?

**Comment by folke** [comment]
@klokan I'm no longer working on any projects using mapping, so would be great if someone wants to take over maintenance of the typings.

@HarelM makes sense to integrate the typings into the repo for sure.

**Comment by HarelM** [comment]
I don't mind taking over the maintenance of the typings as long as it's in this repo so that there's no need to do anything special when releasing a version...
Unfortunately, I don't have maintainers permission so all I can do it a pull request, but I need to know if this is the direction that the @maintainers would like to go before sending the PR. I can check in the slack of the project to make sure...

**Comment by HarelM** [comment]
I've created a pull request. Please let me know what else is missing tin order o move this forward.
