### ISSUE TITLE
Support other contexts than WebGL1 in unit tests

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#2605]
The unit tests use a NodeJS WebGL implementation (https://github.com/stackgl/headless-gl), that unfortunately only supports WebGL1.

The rest of the codebase is on webgl2 now, so this is the last piece blocking us from adopting more webgl2-only features, and from letting go of all the mocking.

It would be great to use a proper webgl2 instance for unit tests.

**Comment by birkskyum** [comment]
This is the result:

Test Suites: 31 failed, 86 passed, 117 total
Tests:       526 failed, 969 passed, 1495 total

My impression is that the failing tests are really not suitable as unit tests, but more like browser tests - i.e. testing drag rotate etc.

**Comment by HarelM** [comment]
Would be interesting to see what type of failures you get, and how complicated it is to solve them.
If it's related to some unimplemented method in gl context or some comparison around images etc.
It's OK to mock the browser in order to do a unit test, even for drag rotate for example as a lot of the code is already mocked (especially the DOM stuff).
But it might also be easier to just migrate to running the test in a browser, IDK.
I fear that it will be less stable even than the render tests and then we might not believe when a test fails, which is not a great place to be at.

**Comment by birkskyum** [comment]
All the state.test.ts tests create a context:

```ts
const context = new Context(gl(10, 10) as any);
```

Which it amongst other things use to get a lot webgl parameters like `context.gl.LEQUAL`

**Comment by HarelM** [comment]
yea, the tests in map are probably more e2e than really unit tests.
Having said that, you can create an mock gl object and pass it to the context to mock stuff that are related to the running test.
I'm not sure how different it is than actually using the `gl` package though...
Bottom line, I'm not sure how important it is to move the unit tests to webgl2 as we are mainly mocking things up.
If there are unit tests that are using webgl2 features, we can gradually mock the relevant part in those I guess...
But again, I'll need an example to actually say something smart...

**Comment by birkskyum** [comment]
Okay, let's take it when something starts to break. It should be possible to adopt the layout qualifiers #2604 without breaking the unit tests, because the it's only the shader api that changes. Closed until a braking case show up.
