### ISSUE TITLE
Popup .trackPointer() changes cursor to pointer forever

### ISSUE THREAD

**Issue by Creatium** [maplibre/maplibre-gl-js#3405]
When adding "trackPointer()" to the popup, it changes cursor to pointer when hovering over a feature. It is then impossible to change it back to "default", even if setting it in the code.

This results in cursor being a pointer even if its not hovering any of the features and popup is not showing or is removed.

Replication (the code is taken straight from the documentation, just added the method to the popup on line 159): https://jsfiddle.net/Lynxe7tu/

As I understand, "trackPointer" sets cursor to pointer in the library itself. But then if I hide the popup on "mouseleave" it does not allow to set cursor to "default". User setting should be preferred.

**Comment by HarelM** [comment]
I'm not sure this is the right usage of `trackPointer`, but I might be missing something obvious.
https://github.com/maplibre/maplibre-gl-js/blob/2fa9195662c2bb29b2e99df31995815b072ef017/src/ui/popup.ts#L297

`trackPointer` basically sets some css classes to the canvas and map, which are not cleaned in the code you shared.
It might be that there's a need to clean them and that there are bugs in the code, but I'm not sure I fully understand the use case here.

**Comment by HarelM** [comment]
Your usage of the popup isn't really tracking the mouse movement in your example.
The idea behind `trackPointer` is that when you hover over the map, you'll have a popup that follows the mouse movement and show that popup above the mouse pointer.

In your example, you open the popup when hovering over the marker, which doesn't need the `trackPointer` in order to do that.

I'm not saying there's no bug here, don't get me wrong, but I'm not sure the example is a good example of the bug.
When setting `trackPointer` the mouse shape changes to `pointer`, which might not be optimal, but does make sense.

My mouse isn't visible in this screen capture, but it's under the "hello" as a `pointer` and not as a `hand`:
![image](https://github.com/maplibre/maplibre-gl-js/assets/3269297/83ecfdbf-8213-44ca-856f-831837dc554e)

I hope this clarifies what I meant...

**Comment by HarelM** [comment]
OK, I found a workaround.
See here:
https://jsfiddle.net/qtaLvyjk/

Basically, adding `setLngLat([0,0])` on `mouseleave` will reset the relevant css classes and will stop the override of the cursor.

The bug remains - there's a need to clean these classes when removing the popup, not just when setting `setLngLat`.
