### ISSUE TITLE
Map option "hash" is overwriting all URL hashes and parameters

### ISSUE THREAD

**Issue by popkinj** [maplibre/maplibre-gl-js#3559]
**maplibre-gl-js version**: 3.6.2

**browser**: Chromium

### Expected Behavior
When setting the map option `hash: true`... the location/pitch etc is stored within the browser URL. This works great. However, when providing a string instead a boolean values it is supposed to allow for **other** (non Maplibre) hash or query parameters to be maintained. This is documented within the [map options](https://maplibre.org/maplibre-gl-js/docs/API/types/maplibregl.MapOptions/)

### Actual Behavior
When adding a custom query parameter like `https://map.name?param=blah#loc=x/y/z.` The `?param=blah` gets erased when moving the map around. Same happens when the parameter is within the hash like this `https://map.name#loc=x/y/z&param=blah`. In both cases, when moving the map the URL turns into `https://map.name#loc=x/y/z.`.

### Notes

:bulb: I'm developing with Svelte and Svelte-kit. Is it possible there is a front end router collision happening.

I'm working on getting an example of this running. Will provide a PR if this turns out to be a true bug.

**Comment by acalcutt** [comment]
I've done some testing with trying to pass parameters with the hash option, and I can confirm with `hash: true` that it was very hard to pass parameters. I actually noticed initially trying to test this callback feature for maplibre-gl-inspect ( https://github.com/acalcutt/maplibre-gl-inspect/pull/5 ) because that feature does not work right with `hash: true`

After testing, the only alternative I found was instead of setting `hash: true`, you give it a variable name, for example, `hash: 'q'` . If you put a variable name instead of 'true', it makes the hash act a parameter in the url instead of a hash value.

So for example, in my trails page I set `hash: 'q'` and I end up with a url like
https://wifidb.net/demo/trails/trails.html#q=6/45.256/-70.999 
(notice the "q=" in the url, it is now a parameter value)

with using hash as a parmeter, it allows other parameters in your url to work as expected

**Comment by acalcutt** [comment]
Also, you mention if you do use that sting value, that the parameter does not stay?

I just updated my page to 3.6.2, but if i thow "test=1" into my parameters like
https://wifidb.net/demo/trails/trails.html?test=1#q=6/47.105/-70.316
it seems like it stays when i browse the map.

**Comment by popkinj** [comment]
Thanks for your testing @acalcutt .... and for the link to your test page :+1: 

I think I see what is happening. The non-Maplibre variables are maintained if they are present on initial load. However, if they get changed afterwards... like with javascript or something... the url goes back to how the parameters were set on initial page load.

For example, If you were to click your link https://wifidb.net/demo/trails/trails.html?test=1#q=6/47.105/-70.316. Then, after the map loads... change the `test=1` to `test=2`. After moving the map it switched back to the original value `test=1`.

Are you able to see this behavior as well? If so, do you think this is the intended behavior?

Thanks again.

**Comment by popkinj** [comment]
Hmmmm.... Looking at this further. If you use javascript to update the window.history object, everything works as expected. ie, a new url parameter is preserved on map navigation. So maybe this is the best behavior after all.

After going to @acalcutt 's test page I entered the following in the console: 
```javascript
window.history.replaceState(null,"","https://wifidb.net/demo/trails/trails.html?test=5#q=6/47.105/-70.316")
```
Then the new `test=5` parameter was maintained after using the map. This makes sense. I think you should only update the URL with javascript anyway.

**Comment by popkinj** [comment]
This is working fine.
