### ISSUE TITLE
getData returns invalid geojson

### ISSUE THREAD

**Issue by risusinf** [maplibre/maplibre-gl-js#4693]
map.getSource.getData returns feature with rearrenged coordinates, that gets flagged over at geojsonlint as breaking right-hand rule

Top coordinates are initial ones that were set with setData, bottoms are retrieved via getData:
![Снимок экрана_20240912_013437](https://github.com/user-attachments/assets/c9ae5698-f697-4ab8-ae53-335448f2de1e)

To reproduce:
1. Get a valid polygon
2. Set it to a source
3. Get it back from the source

Example: https://jsbin.com/toperirawa/edit?html,output

**Comment by HarelM** [comment]
I tend to think this is intentional in order to be able to fill this polygon if needed.
See the code here:
https://github.com/maplibre/maplibre-gl-js/blob/41e5b32f5bd6264cbc4a8b38210ec6a410152259/src/source/geojson_worker_source.ts#L193

I haven't dug deeply into it, but I tend to say that this is by design.

**Comment by risusinf** [comment]
Not sure what do you mean by 'filling'.

Maybe there is rationale behind it but i i can't say i like the idea of my data being returned to me altered without request and in a way that geojson standart considers it invalid.
