### ISSUE TITLE
Larger tile boundaries

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#4803]
**maplibre-gl-js version**:
5.0.0-pre.1
**browser**:
chrome on ubuntu
### Steps to Trigger Behavior

 1.
 2.
 3.

#### 5.0.0-pre.1

https://jsbin.com/gacagon/edit?html,output

![image](https://github.com/user-attachments/assets/69b5d444-39bb-4da8-9e46-099e19b80626)

#### 4.7.1

https://jsbin.com/didahib/edit?html,output

![image](https://github.com/user-attachments/assets/ca19cb02-e4f2-4e68-b1c0-63c0595c6cad)

### Expected Behavior

Tile content should be clipped at the tile boundary. 

### Actual Behavior

Tile content is larger than tile boundary. Depending on content, margin seems different (source layer "earth" extends more than source layer "landuse"). This creates a visual border effect which is notable during tile loading on slow connections.

**Comment by HarelM** [comment]
Thanks for taking the time to report this, I don't remember globe code touching tile boundaries in terms of clippling, but the fact don't lie :-)

**Comment by kubapelc** [comment]
I will definitely investigate this. Globe modified clipping a lot, since curved tiles are a lot more prone to seams at the border, especially with the fill layer, which can have much finer geometry than the stencil mask and thus extend beyond it vertically. I'm not sure there will be a good solution to this that changes the clipping logic itself, but it should be possible to detect tiles that lack a neighbour and use a different clipping mask for them.
