### ISSUE TITLE
flyTo has discontinuous jump for some motions to points close to 180degrees of longitude.

### ISSUE THREAD

**Issue by FunMiles** [maplibre/maplibre-gl-js#62]
**maplibre-gl-js version**:
1.13.0-rc.3
**browser**:
chrome safari firefox
### Steps to Trigger Behavior
Use flyTo from a position of `{center: [99.63705, 25.00275], zoom: 2}` to `{center: [175.3655, 35.7514], zoom: 0}` as long as the window containing the map has  width to height that is not too large.
See the simple demonstration link below. 

### Link to Demonstration
Resize the window so that the map is not too elongated and so that the window is large. Then click on `ToOne` let the motion end, the click on `ToTwo`
https://codepen.io/funmiles/pen/vYXqPNp

### Expected Behavior
When clicking on `ToTwo`, the map should move left so that the center's longitude goes monotonically between 99 and 175.

### Actual Behavior
The center's longitude starts to decrease, going into negative numbers (down to about -18) and then jumps to the final value.

### Notes
The problem disappears if the final zoom is 1.
The problem is much less pronounced if the window is small.

**Comment by JannikGM** [comment]
I added `map.setRenderWorldCopies(false)` and recorded this video of the bug, it also happens when moving from location two, to location two:


https://user-images.githubusercontent.com/72194488/112128736-02672900-8bc7-11eb-9fb0-655055a994f2.mov


This should help with having an even more minimalistic test case.

---

I'd assume that zooming out to far will attempt to center the map, fighting with the actual animation.
We are already zoomed out very far but the transition would zoom out further; also, as you correctly noticed, it doesn't happen with `zoom: 1` - presumably because there's more headroom.

In general, I have seen issues with bad `zoom` and bad `unproject` in the past, so I'd make them prime suspects.

So, for debugging this, I'd recommend to ensure the zoom is not going out of bounds:

https://github.com/maplibre/maplibre-gl-js/blob/256d1b898f1bd21f829977d4dec602a7f649f5a0/src/ui/camera.js#L1133

If that's not it, also check if this `unproject` location is correct:

https://github.com/maplibre/maplibre-gl-js/blob/256d1b898f1bd21f829977d4dec602a7f649f5a0/src/ui/camera.js#L1148

If those are not responsible, I'd recommend to visualize these variables:

https://github.com/maplibre/maplibre-gl-js/blob/256d1b898f1bd21f829977d4dec602a7f649f5a0/src/ui/camera.js#L1035-L1040

**Comment by alunux** [comment]
Sorry, any update on this?

**Comment by HarelM** [comment]
Nope, feel free to open a PR if this is something that is close to your heart.
