### ISSUE TITLE
Module 'maplibre-gl' has no exported member 'GeoJSONSource'

### ISSUE THREAD

**Issue by sebisteiner** [maplibre/maplibre-gl-js#801]
**maplibre-gl-js version**: 2.0.2

### Steps to Trigger Behavior

 1. `import {GeoJSONSource} from 'maplibre-gl';`

### Expected Behavior
`GeoJSONSource` type should be importable. As it was in v1.15.2.

### Actual Behavior
`Module 'maplibre-gl' has no exported member 'GeoJSONSource'`

**Comment by HarelM** [comment]
I think there's an open PR on this that I didn't get an answer about the review I did...

**Comment by sebisteiner** [comment]
Thank you, I just saw the PR: https://github.com/maplibre/maplibre-gl-js/pull/608

Do you think it could be merged?

**Comment by HarelM** [comment]
I think this PR is not full. GeoJSON source is not the only one... This is why it's not merged.
Feel free to submit a fuller PR.

**Comment by DartWelder** [comment]
The same crap with the Point object. But it works on version 2.0.2 and fails on 2.0.5

**Comment by HarelM** [comment]
Crap is not an appropriate word... 
Point object was moved to mapbox point-geometry package in 2.0.5, so you can use it from there.
If you don't like this library you don't have to use it, but please try not to insult the volunteering people who dedicate their free time to maintain it.
As I said in my previous comment, you are more than welcome to fix it and submit a PR...

**Comment by DartWelder** [comment]
no no no, dude I didn't mean something offensive)

**Comment by HarelM** [comment]
No worries :-) There's a problem between the generated types and what the package exposes due to how it is complied and packed into a UMD module. This is creating a lot of noise, Point is just one example, and GeoJSON is another.
If anyone has a good idea how to solve it I'd be very much interested to know. I found some hacks which I'm not very proud of, but they seem to allow working decently with the types and also generate things automatically.
It's not ideal, but it's better than manual editing and sync issues I believe.

**Comment by mattmyne** [comment]
I'm not sure if it helps with the original issue but I was able to use `GeoJSONSourceSpecification` as a substitute type for the missing `GeoJSONSource` I had originally been using in my typescript.

**Comment by sebisteiner** [comment]
> If anyone has a good idea how to solve it I'd be very much interested to know.
I'm not experienced with TypeScript definitions and their generation.

So I just created a small PR that exports all source types. See https://github.com/maplibre/maplibre-gl-js/pull/946
